package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DepartmentRevenueId generated by hbm2java
 */
@Embeddable
public class DepartmentRevenueId implements java.io.Serializable {

	private String id;
	private String code;
	private String label;
	private String periodId;
	private String periodCode;
	private BigDecimal depRevenue;

	public DepartmentRevenueId() {
	}

	public DepartmentRevenueId(String id, String code, String label,
			String periodId, String periodCode) {
		this.id = id;
		this.code = code;
		this.label = label;
		this.periodId = periodId;
		this.periodCode = periodCode;
	}

	public DepartmentRevenueId(String id, String code, String label,
			String periodId, String periodCode, BigDecimal depRevenue) {
		this.id = id;
		this.code = code;
		this.label = label;
		this.periodId = periodId;
		this.periodCode = periodCode;
		this.depRevenue = depRevenue;
	}

	@Column(name = "ID", nullable = false, length = 144)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 40)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "LABEL", nullable = false, length = 120)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "PERIOD_ID", nullable = false, length = 144)
	public String getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(String periodId) {
		this.periodId = periodId;
	}

	@Column(name = "PERIOD_CODE", nullable = false, length = 28)
	public String getPeriodCode() {
		return this.periodCode;
	}

	public void setPeriodCode(String periodCode) {
		this.periodCode = periodCode;
	}

	@Column(name = "DEP_REVENUE", precision = 22, scale = 0)
	public BigDecimal getDepRevenue() {
		return this.depRevenue;
	}

	public void setDepRevenue(BigDecimal depRevenue) {
		this.depRevenue = depRevenue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DepartmentRevenueId))
			return false;
		DepartmentRevenueId castOther = (DepartmentRevenueId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null
						&& castOther.getCode() != null && this.getCode()
						.equals(castOther.getCode())))
				&& ((this.getLabel() == castOther.getLabel()) || (this
						.getLabel() != null && castOther.getLabel() != null && this
						.getLabel().equals(castOther.getLabel())))
				&& ((this.getPeriodId() == castOther.getPeriodId()) || (this
						.getPeriodId() != null
						&& castOther.getPeriodId() != null && this
						.getPeriodId().equals(castOther.getPeriodId())))
				&& ((this.getPeriodCode() == castOther.getPeriodCode()) || (this
						.getPeriodCode() != null
						&& castOther.getPeriodCode() != null && this
						.getPeriodCode().equals(castOther.getPeriodCode())))
				&& ((this.getDepRevenue() == castOther.getDepRevenue()) || (this
						.getDepRevenue() != null
						&& castOther.getDepRevenue() != null && this
						.getDepRevenue().equals(castOther.getDepRevenue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result
				+ (getLabel() == null ? 0 : this.getLabel().hashCode());
		result = 37 * result
				+ (getPeriodId() == null ? 0 : this.getPeriodId().hashCode());
		result = 37
				* result
				+ (getPeriodCode() == null ? 0 : this.getPeriodCode()
						.hashCode());
		result = 37
				* result
				+ (getDepRevenue() == null ? 0 : this.getDepRevenue()
						.hashCode());
		return result;
	}

}
