package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT")
public class Department implements java.io.Serializable {

	private String id;
	private String code;
	private String label;
	private Set<RevenueDeptPeriod> revenueDeptPeriods = new HashSet<RevenueDeptPeriod>(
			0);
	private Set<EmplDeptPeriod> emplDeptPeriods = new HashSet<EmplDeptPeriod>(0);

	public Department() {
	}

	public Department(String id, String code) {
		this.id = id;
		this.code = code;
	}

	public Department(String id, String code, String label,
			Set<RevenueDeptPeriod> revenueDeptPeriods,
			Set<EmplDeptPeriod> emplDeptPeriods) {
		this.id = id;
		this.code = code;
		this.label = label;
		this.revenueDeptPeriods = revenueDeptPeriods;
		this.emplDeptPeriods = emplDeptPeriods;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 400)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "LABEL", length = 800)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<RevenueDeptPeriod> getRevenueDeptPeriods() {
		return this.revenueDeptPeriods;
	}

	public void setRevenueDeptPeriods(Set<RevenueDeptPeriod> revenueDeptPeriods) {
		this.revenueDeptPeriods = revenueDeptPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<EmplDeptPeriod> getEmplDeptPeriods() {
		return this.emplDeptPeriods;
	}

	public void setEmplDeptPeriods(Set<EmplDeptPeriod> emplDeptPeriods) {
		this.emplDeptPeriods = emplDeptPeriods;
	}

}
