package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeStatsId generated by hbm2java
 */
@Embeddable
public class EmployeeStatsId implements java.io.Serializable {

	private String matchcode;
	private String code;
	private BigDecimal v01;
	private BigDecimal v02;
	private BigDecimal v03;
	private BigDecimal v04;
	private BigDecimal v05;
	private BigDecimal v06;
	private BigDecimal v07;
	private BigDecimal v08;
	private BigDecimal v09;
	private BigDecimal v10;
	private BigDecimal v11;
	private BigDecimal v12;
	private BigDecimal v13;
	private String s01;
	private BigDecimal v14;
	private BigDecimal v15;
	private BigDecimal v16;
	private BigDecimal v17;
	private BigDecimal v18;

	public EmployeeStatsId() {
	}

	public EmployeeStatsId(String code) {
		this.code = code;
	}

	public EmployeeStatsId(String matchcode, String code, BigDecimal v01,
			BigDecimal v02, BigDecimal v03, BigDecimal v04, BigDecimal v05,
			BigDecimal v06, BigDecimal v07, BigDecimal v08, BigDecimal v09,
			BigDecimal v10, BigDecimal v11, BigDecimal v12, BigDecimal v13,
			String s01, BigDecimal v14, BigDecimal v15, BigDecimal v16,
			BigDecimal v17, BigDecimal v18) {
		this.matchcode = matchcode;
		this.code = code;
		this.v01 = v01;
		this.v02 = v02;
		this.v03 = v03;
		this.v04 = v04;
		this.v05 = v05;
		this.v06 = v06;
		this.v07 = v07;
		this.v08 = v08;
		this.v09 = v09;
		this.v10 = v10;
		this.v11 = v11;
		this.v12 = v12;
		this.v13 = v13;
		this.s01 = s01;
		this.v14 = v14;
		this.v15 = v15;
		this.v16 = v16;
		this.v17 = v17;
		this.v18 = v18;
	}

	@Column(name = "MATCHCODE", length = 50)
	public String getMatchcode() {
		return this.matchcode;
	}

	public void setMatchcode(String matchcode) {
		this.matchcode = matchcode;
	}

	@Column(name = "CODE", nullable = false, length = 28)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "V01", precision = 22, scale = 0)
	public BigDecimal getV01() {
		return this.v01;
	}

	public void setV01(BigDecimal v01) {
		this.v01 = v01;
	}

	@Column(name = "V02", precision = 22, scale = 0)
	public BigDecimal getV02() {
		return this.v02;
	}

	public void setV02(BigDecimal v02) {
		this.v02 = v02;
	}

	@Column(name = "V03", precision = 22, scale = 0)
	public BigDecimal getV03() {
		return this.v03;
	}

	public void setV03(BigDecimal v03) {
		this.v03 = v03;
	}

	@Column(name = "V04", precision = 22, scale = 0)
	public BigDecimal getV04() {
		return this.v04;
	}

	public void setV04(BigDecimal v04) {
		this.v04 = v04;
	}

	@Column(name = "V05", precision = 22, scale = 0)
	public BigDecimal getV05() {
		return this.v05;
	}

	public void setV05(BigDecimal v05) {
		this.v05 = v05;
	}

	@Column(name = "V06", precision = 22, scale = 0)
	public BigDecimal getV06() {
		return this.v06;
	}

	public void setV06(BigDecimal v06) {
		this.v06 = v06;
	}

	@Column(name = "V07", precision = 22, scale = 0)
	public BigDecimal getV07() {
		return this.v07;
	}

	public void setV07(BigDecimal v07) {
		this.v07 = v07;
	}

	@Column(name = "V08", precision = 22, scale = 0)
	public BigDecimal getV08() {
		return this.v08;
	}

	public void setV08(BigDecimal v08) {
		this.v08 = v08;
	}

	@Column(name = "V09", precision = 22, scale = 0)
	public BigDecimal getV09() {
		return this.v09;
	}

	public void setV09(BigDecimal v09) {
		this.v09 = v09;
	}

	@Column(name = "V10", precision = 22, scale = 0)
	public BigDecimal getV10() {
		return this.v10;
	}

	public void setV10(BigDecimal v10) {
		this.v10 = v10;
	}

	@Column(name = "V11", precision = 22, scale = 0)
	public BigDecimal getV11() {
		return this.v11;
	}

	public void setV11(BigDecimal v11) {
		this.v11 = v11;
	}

	@Column(name = "V12", precision = 22, scale = 0)
	public BigDecimal getV12() {
		return this.v12;
	}

	public void setV12(BigDecimal v12) {
		this.v12 = v12;
	}

	@Column(name = "V13", precision = 22, scale = 0)
	public BigDecimal getV13() {
		return this.v13;
	}

	public void setV13(BigDecimal v13) {
		this.v13 = v13;
	}

	@Column(name = "S01", length = 500)
	public String getS01() {
		return this.s01;
	}

	public void setS01(String s01) {
		this.s01 = s01;
	}

	@Column(name = "V14", precision = 22, scale = 0)
	public BigDecimal getV14() {
		return this.v14;
	}

	public void setV14(BigDecimal v14) {
		this.v14 = v14;
	}

	@Column(name = "V15", precision = 22, scale = 0)
	public BigDecimal getV15() {
		return this.v15;
	}

	public void setV15(BigDecimal v15) {
		this.v15 = v15;
	}

	@Column(name = "V16", precision = 22, scale = 0)
	public BigDecimal getV16() {
		return this.v16;
	}

	public void setV16(BigDecimal v16) {
		this.v16 = v16;
	}

	@Column(name = "V17", precision = 22, scale = 0)
	public BigDecimal getV17() {
		return this.v17;
	}

	public void setV17(BigDecimal v17) {
		this.v17 = v17;
	}

	@Column(name = "V18", precision = 22, scale = 0)
	public BigDecimal getV18() {
		return this.v18;
	}

	public void setV18(BigDecimal v18) {
		this.v18 = v18;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeStatsId))
			return false;
		EmployeeStatsId castOther = (EmployeeStatsId) other;

		return ((this.getMatchcode() == castOther.getMatchcode()) || (this
				.getMatchcode() != null && castOther.getMatchcode() != null && this
				.getMatchcode().equals(castOther.getMatchcode())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null
						&& castOther.getCode() != null && this.getCode()
						.equals(castOther.getCode())))
				&& ((this.getV01() == castOther.getV01()) || (this.getV01() != null
						&& castOther.getV01() != null && this.getV01().equals(
						castOther.getV01())))
				&& ((this.getV02() == castOther.getV02()) || (this.getV02() != null
						&& castOther.getV02() != null && this.getV02().equals(
						castOther.getV02())))
				&& ((this.getV03() == castOther.getV03()) || (this.getV03() != null
						&& castOther.getV03() != null && this.getV03().equals(
						castOther.getV03())))
				&& ((this.getV04() == castOther.getV04()) || (this.getV04() != null
						&& castOther.getV04() != null && this.getV04().equals(
						castOther.getV04())))
				&& ((this.getV05() == castOther.getV05()) || (this.getV05() != null
						&& castOther.getV05() != null && this.getV05().equals(
						castOther.getV05())))
				&& ((this.getV06() == castOther.getV06()) || (this.getV06() != null
						&& castOther.getV06() != null && this.getV06().equals(
						castOther.getV06())))
				&& ((this.getV07() == castOther.getV07()) || (this.getV07() != null
						&& castOther.getV07() != null && this.getV07().equals(
						castOther.getV07())))
				&& ((this.getV08() == castOther.getV08()) || (this.getV08() != null
						&& castOther.getV08() != null && this.getV08().equals(
						castOther.getV08())))
				&& ((this.getV09() == castOther.getV09()) || (this.getV09() != null
						&& castOther.getV09() != null && this.getV09().equals(
						castOther.getV09())))
				&& ((this.getV10() == castOther.getV10()) || (this.getV10() != null
						&& castOther.getV10() != null && this.getV10().equals(
						castOther.getV10())))
				&& ((this.getV11() == castOther.getV11()) || (this.getV11() != null
						&& castOther.getV11() != null && this.getV11().equals(
						castOther.getV11())))
				&& ((this.getV12() == castOther.getV12()) || (this.getV12() != null
						&& castOther.getV12() != null && this.getV12().equals(
						castOther.getV12())))
				&& ((this.getV13() == castOther.getV13()) || (this.getV13() != null
						&& castOther.getV13() != null && this.getV13().equals(
						castOther.getV13())))
				&& ((this.getS01() == castOther.getS01()) || (this.getS01() != null
						&& castOther.getS01() != null && this.getS01().equals(
						castOther.getS01())))
				&& ((this.getV14() == castOther.getV14()) || (this.getV14() != null
						&& castOther.getV14() != null && this.getV14().equals(
						castOther.getV14())))
				&& ((this.getV15() == castOther.getV15()) || (this.getV15() != null
						&& castOther.getV15() != null && this.getV15().equals(
						castOther.getV15())))
				&& ((this.getV16() == castOther.getV16()) || (this.getV16() != null
						&& castOther.getV16() != null && this.getV16().equals(
						castOther.getV16())))
				&& ((this.getV17() == castOther.getV17()) || (this.getV17() != null
						&& castOther.getV17() != null && this.getV17().equals(
						castOther.getV17())))
				&& ((this.getV18() == castOther.getV18()) || (this.getV18() != null
						&& castOther.getV18() != null && this.getV18().equals(
						castOther.getV18())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMatchcode() == null ? 0 : this.getMatchcode().hashCode());
		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result
				+ (getV01() == null ? 0 : this.getV01().hashCode());
		result = 37 * result
				+ (getV02() == null ? 0 : this.getV02().hashCode());
		result = 37 * result
				+ (getV03() == null ? 0 : this.getV03().hashCode());
		result = 37 * result
				+ (getV04() == null ? 0 : this.getV04().hashCode());
		result = 37 * result
				+ (getV05() == null ? 0 : this.getV05().hashCode());
		result = 37 * result
				+ (getV06() == null ? 0 : this.getV06().hashCode());
		result = 37 * result
				+ (getV07() == null ? 0 : this.getV07().hashCode());
		result = 37 * result
				+ (getV08() == null ? 0 : this.getV08().hashCode());
		result = 37 * result
				+ (getV09() == null ? 0 : this.getV09().hashCode());
		result = 37 * result
				+ (getV10() == null ? 0 : this.getV10().hashCode());
		result = 37 * result
				+ (getV11() == null ? 0 : this.getV11().hashCode());
		result = 37 * result
				+ (getV12() == null ? 0 : this.getV12().hashCode());
		result = 37 * result
				+ (getV13() == null ? 0 : this.getV13().hashCode());
		result = 37 * result
				+ (getS01() == null ? 0 : this.getS01().hashCode());
		result = 37 * result
				+ (getV14() == null ? 0 : this.getV14().hashCode());
		result = 37 * result
				+ (getV15() == null ? 0 : this.getV15().hashCode());
		result = 37 * result
				+ (getV16() == null ? 0 : this.getV16().hashCode());
		result = 37 * result
				+ (getV17() == null ? 0 : this.getV17().hashCode());
		result = 37 * result
				+ (getV18() == null ? 0 : this.getV18().hashCode());
		return result;
	}

}
