package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmplDeptPeriod generated by hbm2java
 */
@Entity
@Table(name = "EMPL_DEPT_PERIOD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"FK_EMPLOYEE_ID", "FK_DEPARTMENT_ID", "FK_PERIOD_ID" }))
public class EmplDeptPeriod implements java.io.Serializable {

	private String id;
	private Department department;
	private Period period;
	private Employee employee;

	public EmplDeptPeriod() {
	}

	public EmplDeptPeriod(String id, Department department, Period period,
			Employee employee) {
		this.id = id;
		this.department = department;
		this.period = period;
		this.employee = employee;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_DEPARTMENT_ID", nullable = false)
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_PERIOD_ID", nullable = false)
	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_EMPLOYEE_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

}
