package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Employee2group2period generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE2GROUP2PERIOD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"FK_EMPLOYEE_ID", "FK_GROUP_ID", "FK_PERIOD_ID" }))
public class Employee2group2period implements java.io.Serializable {

	private String id;
	private String fkEmployeeId;
	private String fkGroupId;
	private String fkPeriodId;

	public Employee2group2period() {
	}

	public Employee2group2period(String id, String fkEmployeeId,
			String fkGroupId, String fkPeriodId) {
		this.id = id;
		this.fkEmployeeId = fkEmployeeId;
		this.fkGroupId = fkGroupId;
		this.fkPeriodId = fkPeriodId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "FK_EMPLOYEE_ID", nullable = false, length = 144)
	public String getFkEmployeeId() {
		return this.fkEmployeeId;
	}

	public void setFkEmployeeId(String fkEmployeeId) {
		this.fkEmployeeId = fkEmployeeId;
	}

	@Column(name = "FK_GROUP_ID", nullable = false, length = 144)
	public String getFkGroupId() {
		return this.fkGroupId;
	}

	public void setFkGroupId(String fkGroupId) {
		this.fkGroupId = fkGroupId;
	}

	@Column(name = "FK_PERIOD_ID", nullable = false, length = 144)
	public String getFkPeriodId() {
		return this.fkPeriodId;
	}

	public void setFkPeriodId(String fkPeriodId) {
		this.fkPeriodId = fkPeriodId;
	}

}
