package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InputData generated by hbm2java
 */
@Entity
@Table(name = "INPUT_DATA")
public class InputData implements java.io.Serializable {

	private String id;
	private InputFileType inputFileType;
	private Period period;
	private String matchcode;
	private BigDecimal revenue;

	public InputData() {
	}

	public InputData(String id, InputFileType inputFileType, Period period,
			String matchcode, BigDecimal revenue) {
		this.id = id;
		this.inputFileType = inputFileType;
		this.period = period;
		this.matchcode = matchcode;
		this.revenue = revenue;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_INPUT_FILE_TYPE_ID", nullable = false)
	public InputFileType getInputFileType() {
		return this.inputFileType;
	}

	public void setInputFileType(InputFileType inputFileType) {
		this.inputFileType = inputFileType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_PERIOD_ID", nullable = false)
	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	@Column(name = "MATCHCODE", nullable = false, length = 50)
	public String getMatchcode() {
		return this.matchcode;
	}

	public void setMatchcode(String matchcode) {
		this.matchcode = matchcode;
	}

	@Column(name = "REVENUE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRevenue() {
		return this.revenue;
	}

	public void setRevenue(BigDecimal revenue) {
		this.revenue = revenue;
	}

}
