package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MatchcodeList generated by hbm2java
 */
@Entity
@Table(name = "MATCHCODE_LIST")
public class MatchcodeList implements java.io.Serializable {

	private MatchcodeListId id;

	public MatchcodeList() {
	}

	public MatchcodeList(MatchcodeListId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "matchcode", column = @Column(name = "MATCHCODE", nullable = false, length = 40)),
			@AttributeOverride(name = "firstName", column = @Column(name = "FIRST_NAME", length = 120)),
			@AttributeOverride(name = "lastName", column = @Column(name = "LAST_NAME", nullable = false, length = 120)) })
	public MatchcodeListId getId() {
		return this.id;
	}

	public void setId(MatchcodeListId id) {
		this.id = id;
	}

}
