package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RevenueEmplPeriod generated by hbm2java
 */
@Entity
@Table(name = "REVENUE_EMPL_PERIOD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"FK_EMPLOYEE_ID", "FK_PERIOD_ID" }))
public class RevenueEmplPeriod implements java.io.Serializable {

	private String id;
	private Period period;
	private Employee employee;
	private BigDecimal revenue;

	public RevenueEmplPeriod() {
	}

	public RevenueEmplPeriod(String id, Period period, Employee employee) {
		this.id = id;
		this.period = period;
		this.employee = employee;
	}

	public RevenueEmplPeriod(String id, Period period, Employee employee,
			BigDecimal revenue) {
		this.id = id;
		this.period = period;
		this.employee = employee;
		this.revenue = revenue;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_PERIOD_ID", nullable = false)
	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_EMPLOYEE_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "REVENUE", precision = 22, scale = 0)
	public BigDecimal getRevenue() {
		return this.revenue;
	}

	public void setRevenue(BigDecimal revenue) {
		this.revenue = revenue;
	}

}
