package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TargetPercentRangeId generated by hbm2java
 */
@Embeddable
public class TargetPercentRangeId implements java.io.Serializable {

	private String id;
	private String fkTargetPeriodId;
	private BigDecimal targetMinRange;
	private BigDecimal targetMaxRange;
	private BigDecimal targetBonus;

	public TargetPercentRangeId() {
	}

	public TargetPercentRangeId(String id, String fkTargetPeriodId,
			BigDecimal targetMaxRange, BigDecimal targetBonus) {
		this.id = id;
		this.fkTargetPeriodId = fkTargetPeriodId;
		this.targetMaxRange = targetMaxRange;
		this.targetBonus = targetBonus;
	}

	public TargetPercentRangeId(String id, String fkTargetPeriodId,
			BigDecimal targetMinRange, BigDecimal targetMaxRange,
			BigDecimal targetBonus) {
		this.id = id;
		this.fkTargetPeriodId = fkTargetPeriodId;
		this.targetMinRange = targetMinRange;
		this.targetMaxRange = targetMaxRange;
		this.targetBonus = targetBonus;
	}

	@Column(name = "ID", nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "FK_TARGET_PERIOD_ID", nullable = false, length = 36)
	public String getFkTargetPeriodId() {
		return this.fkTargetPeriodId;
	}

	public void setFkTargetPeriodId(String fkTargetPeriodId) {
		this.fkTargetPeriodId = fkTargetPeriodId;
	}

	@Column(name = "TARGET_MIN_RANGE", precision = 22, scale = 0)
	public BigDecimal getTargetMinRange() {
		return this.targetMinRange;
	}

	public void setTargetMinRange(BigDecimal targetMinRange) {
		this.targetMinRange = targetMinRange;
	}

	@Column(name = "TARGET_MAX_RANGE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTargetMaxRange() {
		return this.targetMaxRange;
	}

	public void setTargetMaxRange(BigDecimal targetMaxRange) {
		this.targetMaxRange = targetMaxRange;
	}

	@Column(name = "TARGET_BONUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTargetBonus() {
		return this.targetBonus;
	}

	public void setTargetBonus(BigDecimal targetBonus) {
		this.targetBonus = targetBonus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TargetPercentRangeId))
			return false;
		TargetPercentRangeId castOther = (TargetPercentRangeId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getFkTargetPeriodId() == castOther
						.getFkTargetPeriodId()) || (this.getFkTargetPeriodId() != null
						&& castOther.getFkTargetPeriodId() != null && this
						.getFkTargetPeriodId().equals(
								castOther.getFkTargetPeriodId())))
				&& ((this.getTargetMinRange() == castOther.getTargetMinRange()) || (this
						.getTargetMinRange() != null
						&& castOther.getTargetMinRange() != null && this
						.getTargetMinRange().equals(
								castOther.getTargetMinRange())))
				&& ((this.getTargetMaxRange() == castOther.getTargetMaxRange()) || (this
						.getTargetMaxRange() != null
						&& castOther.getTargetMaxRange() != null && this
						.getTargetMaxRange().equals(
								castOther.getTargetMaxRange())))
				&& ((this.getTargetBonus() == castOther.getTargetBonus()) || (this
						.getTargetBonus() != null
						&& castOther.getTargetBonus() != null && this
						.getTargetBonus().equals(castOther.getTargetBonus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getFkTargetPeriodId() == null ? 0 : this
						.getFkTargetPeriodId().hashCode());
		result = 37
				* result
				+ (getTargetMinRange() == null ? 0 : this.getTargetMinRange()
						.hashCode());
		result = 37
				* result
				+ (getTargetMaxRange() == null ? 0 : this.getTargetMaxRange()
						.hashCode());
		result = 37
				* result
				+ (getTargetBonus() == null ? 0 : this.getTargetBonus()
						.hashCode());
		return result;
	}

}
