package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TargetPercentRange generated by hbm2java
 */
@Entity
@Table(name = "TARGET_PERCENT_RANGE")
public class TargetPercentRange implements java.io.Serializable {

	private TargetPercentRangeId id;

	public TargetPercentRange() {
	}

	public TargetPercentRange(TargetPercentRangeId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 36)),
			@AttributeOverride(name = "fkTargetPeriodId", column = @Column(name = "FK_TARGET_PERIOD_ID", nullable = false, length = 36)),
			@AttributeOverride(name = "targetMinRange", column = @Column(name = "TARGET_MIN_RANGE", precision = 22, scale = 0)),
			@AttributeOverride(name = "targetMaxRange", column = @Column(name = "TARGET_MAX_RANGE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "targetBonus", column = @Column(name = "TARGET_BONUS", nullable = false, precision = 22, scale = 0)) })
	public TargetPercentRangeId getId() {
		return this.id;
	}

	public void setId(TargetPercentRangeId id) {
		this.id = id;
	}

}
