package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TargetLevels generated by hbm2java
 */
@Entity
@Table(name = "TARGET_LEVELS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"FK_TARGET_PERIOD_ID", "TARGET_PERCENT" }))
public class TargetLevels implements java.io.Serializable {

	private String id;
	private TargetPeriod targetPeriod;
	private BigDecimal targetPercent;
	private BigDecimal targetBonus;

	public TargetLevels() {
	}

	public TargetLevels(String id, TargetPeriod targetPeriod,
			BigDecimal targetPercent, BigDecimal targetBonus) {
		this.id = id;
		this.targetPeriod = targetPeriod;
		this.targetPercent = targetPercent;
		this.targetBonus = targetBonus;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_TARGET_PERIOD_ID", nullable = false)
	public TargetPeriod getTargetPeriod() {
		return this.targetPeriod;
	}

	public void setTargetPeriod(TargetPeriod targetPeriod) {
		this.targetPeriod = targetPeriod;
	}

	@Column(name = "TARGET_PERCENT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTargetPercent() {
		return this.targetPercent;
	}

	public void setTargetPercent(BigDecimal targetPercent) {
		this.targetPercent = targetPercent;
	}

	@Column(name = "TARGET_BONUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTargetBonus() {
		return this.targetBonus;
	}

	public void setTargetBonus(BigDecimal targetBonus) {
		this.targetBonus = targetBonus;
	}

}
