package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TrzUser generated by hbm2java
 */
@Entity
@Table(name = "TRZ_USER")
public class TrzUser implements java.io.Serializable {

	private String id;
	private String login;
	private String password;
	private String tabs;

	public TrzUser() {
	}

	public TrzUser(String id, String login, String password) {
		this.id = id;
		this.login = login;
		this.password = password;
	}

	public TrzUser(String id, String login, String password, String tabs) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.tabs = tabs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "LOGIN", nullable = false, length = 100)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "TABS", length = 1000)
	public String getTabs() {
		return this.tabs;
	}

	public void setTabs(String tabs) {
		this.tabs = tabs;
	}

}
