package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserDepartmentId generated by hbm2java
 */
@Embeddable
public class UserDepartmentId implements java.io.Serializable {

	private String matchcode;
	private String depName;
	private String depId;

	public UserDepartmentId() {
	}

	public UserDepartmentId(String matchcode, String depName, String depId) {
		this.matchcode = matchcode;
		this.depName = depName;
		this.depId = depId;
	}

	@Column(name = "MATCHCODE", nullable = false, length = 40)
	public String getMatchcode() {
		return this.matchcode;
	}

	public void setMatchcode(String matchcode) {
		this.matchcode = matchcode;
	}

	@Column(name = "DEP_NAME", nullable = false, length = 120)
	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	@Column(name = "DEP_ID", nullable = false, length = 40)
	public String getDepId() {
		return this.depId;
	}

	public void setDepId(String depId) {
		this.depId = depId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserDepartmentId))
			return false;
		UserDepartmentId castOther = (UserDepartmentId) other;

		return ((this.getMatchcode() == castOther.getMatchcode()) || (this
				.getMatchcode() != null && castOther.getMatchcode() != null && this
				.getMatchcode().equals(castOther.getMatchcode())))
				&& ((this.getDepName() == castOther.getDepName()) || (this
						.getDepName() != null && castOther.getDepName() != null && this
						.getDepName().equals(castOther.getDepName())))
				&& ((this.getDepId() == castOther.getDepId()) || (this
						.getDepId() != null && castOther.getDepId() != null && this
						.getDepId().equals(castOther.getDepId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMatchcode() == null ? 0 : this.getMatchcode().hashCode());
		result = 37 * result
				+ (getDepName() == null ? 0 : this.getDepName().hashCode());
		result = 37 * result
				+ (getDepId() == null ? 0 : this.getDepId().hashCode());
		return result;
	}

}
