package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserDepartment generated by hbm2java
 */
@Entity
@Table(name = "USER_DEPARTMENT")
public class UserDepartment implements java.io.Serializable {

	private UserDepartmentId id;

	public UserDepartment() {
	}

	public UserDepartment(UserDepartmentId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "matchcode", column = @Column(name = "MATCHCODE", nullable = false, length = 40)),
			@AttributeOverride(name = "depName", column = @Column(name = "DEP_NAME", nullable = false, length = 120)),
			@AttributeOverride(name = "depId", column = @Column(name = "DEP_ID", nullable = false, length = 40)) })
	public UserDepartmentId getId() {
		return this.id;
	}

	public void setId(UserDepartmentId id) {
		this.id = id;
	}

}
