package com.consultancygrid.trz.model;

// Generated Oct 20, 2014 12:53:50 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT")
public class Department implements java.io.Serializable {

	
	
	
	private UUID id;
	
	private String code;
	private String label;
	private Set<RevenueDeptPeriod> revenueDeptPeriods = new HashSet<RevenueDeptPeriod>(
			0);
	private Set<EmplDeptPeriod> emplDeptPeriods = new HashSet<EmplDeptPeriod>(0);

	public Department() {
	}

	public Department(UUID id, String code) {
		this.id = id;
		this.code = code;
	}

	public Department(UUID id, String code, String label,
			Set<RevenueDeptPeriod> revenueDeptPeriods,
			Set<EmplDeptPeriod> emplDeptPeriods) {
		this.id = id;
		this.code = code;
		this.label = label;
		this.revenueDeptPeriods = revenueDeptPeriods;
		this.emplDeptPeriods = emplDeptPeriods;
	}

	
	@GenericGenerator(name = "dep_trz_uuid_gen", strategy = "com.consultancygrid.trz.model.CustomUUIDGenerator")
	@Id
	@GeneratedValue(generator = "dep_trz_uuid_gen")
	@Type(type = "com.consultancygrid.trz.model.UUIDType")
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 400)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "LABEL", length = 800)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<RevenueDeptPeriod> getRevenueDeptPeriods() {
		return this.revenueDeptPeriods;
	}

	public void setRevenueDeptPeriods(Set<RevenueDeptPeriod> revenueDeptPeriods) {
		this.revenueDeptPeriods = revenueDeptPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<EmplDeptPeriod> getEmplDeptPeriods() {
		return this.emplDeptPeriods;
	}

	public void setEmplDeptPeriods(Set<EmplDeptPeriod> emplDeptPeriods) {
		this.emplDeptPeriods = emplDeptPeriods;
	}

}
