package com.consultancygrid.trz.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DepartmentRevenue generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT_REVENUE")
public class DepartmentRevenue implements java.io.Serializable {

	private DepartmentRevenueId id;

	public DepartmentRevenue() {
	}

	public DepartmentRevenue(DepartmentRevenueId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 144)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", nullable = false, length = 40)),
			@AttributeOverride(name = "label", column = @Column(name = "LABEL", nullable = false, length = 120)),
			@AttributeOverride(name = "periodId", column = @Column(name = "PERIOD_ID", nullable = false, length = 144)),
			@AttributeOverride(name = "periodCode", column = @Column(name = "PERIOD_CODE", nullable = false, length = 28)),
			@AttributeOverride(name = "depRevenue", column = @Column(name = "DEP_REVENUE", precision = 22, scale = 0)) })
	public DepartmentRevenueId getId() {
		return this.id;
	}

	public void setId(DepartmentRevenueId id) {
		this.id = id;
	}

}
