package com.consultancygrid.trz.model;

// Generated May 11, 2015 3:52:18 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EmployeeStats generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE_STATS")
public class EmployeeStats implements java.io.Serializable {

	private EmployeeStatsId id;

	public EmployeeStats() {
	}

	public EmployeeStats(EmployeeStatsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "matchcode", column = @Column(name = "MATCHCODE", length = 50)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", nullable = false, length = 28)),
			@AttributeOverride(name = "v01", column = @Column(name = "V01", precision = 22, scale = 0)),
			@AttributeOverride(name = "v02", column = @Column(name = "V02", precision = 22, scale = 0)),
			@AttributeOverride(name = "v03", column = @Column(name = "V03", precision = 22, scale = 0)),
			@AttributeOverride(name = "v04", column = @Column(name = "V04", precision = 22, scale = 0)),
			@AttributeOverride(name = "v05", column = @Column(name = "V05", precision = 22, scale = 0)),
			@AttributeOverride(name = "v06", column = @Column(name = "V06", precision = 22, scale = 0)),
			@AttributeOverride(name = "v07", column = @Column(name = "V07", precision = 22, scale = 0)),
			@AttributeOverride(name = "v08", column = @Column(name = "V08", precision = 22, scale = 0)),
			@AttributeOverride(name = "v09", column = @Column(name = "V09", precision = 22, scale = 0)),
			@AttributeOverride(name = "v10", column = @Column(name = "V10", precision = 22, scale = 0)),
			@AttributeOverride(name = "v11", column = @Column(name = "V11", precision = 22, scale = 0)),
			@AttributeOverride(name = "v12", column = @Column(name = "V12", precision = 22, scale = 0)),
			@AttributeOverride(name = "v13", column = @Column(name = "V13", precision = 22, scale = 0)),
			@AttributeOverride(name = "s01", column = @Column(name = "S01", length = 500)),
			@AttributeOverride(name = "v14", column = @Column(name = "V14", precision = 22, scale = 0)),
			@AttributeOverride(name = "v15", column = @Column(name = "V15", precision = 22, scale = 0)),
			@AttributeOverride(name = "v16", column = @Column(name = "V16", precision = 22, scale = 0)),
			@AttributeOverride(name = "v17", column = @Column(name = "V17", precision = 22, scale = 0)),
			@AttributeOverride(name = "v18", column = @Column(name = "V18", precision = 22, scale = 0)) })
	public EmployeeStatsId getId() {
		return this.id;
	}

	public void setId(EmployeeStatsId id) {
		this.id = id;
	}

}
