package com.consultancygrid.trz.model;

// Generated Oct 20, 2014 12:53:50 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE")
public class Employee implements java.io.Serializable {

	private UUID id;
	private String firstName;
	private String lastName;
	private String isActive;
	private String matchCode;
	private Set<RevenueEmplPeriod> revenueEmplPeriods = new HashSet<RevenueEmplPeriod>(
			0);
	private Set<EmplDeptPeriod> emplDeptPeriods = new HashSet<EmplDeptPeriod>(0);
	private Set<EmployeeSalary> employeeSalaries = new HashSet<EmployeeSalary>(
			0);
	private Set<EmployeeSettings> employeeSettingses = new HashSet<EmployeeSettings>(
			0);

	public Employee() {
	}

	public Employee(UUID id, String firstName, String lastName, String isActive) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.isActive = isActive;
	}

	public Employee(UUID id, String firstName, String lastName,
			String isActive, String matchCode,
			Set<RevenueEmplPeriod> revenueEmplPeriods,
			Set<EmplDeptPeriod> emplDeptPeriods,
			Set<EmployeeSalary> employeeSalaries,
			Set<EmployeeSettings> employeeSettingses) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.isActive = isActive;
		this.matchCode = matchCode;
		this.revenueEmplPeriods = revenueEmplPeriods;
		this.emplDeptPeriods = emplDeptPeriods;
		this.employeeSalaries = employeeSalaries;
		this.employeeSettingses = employeeSettingses;
	}

	@GenericGenerator(name = "e_trz_uuid_gen", strategy = "com.consultancygrid.trz.model.CustomUUIDGenerator")
	@Id
	@GeneratedValue(generator = "e_trz_uuid_gen")
	@Type(type = "com.consultancygrid.trz.model.UUIDType")
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 400)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 400)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "IS_ACTIVE", nullable = false, length = 4)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "MATCHCODE", precision = 22, scale = 0)
	public String getMatchCode() {
		return this.matchCode;
	}

	public void setMatchCode(String matchCode) {
		this.matchCode = matchCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<RevenueEmplPeriod> getRevenueEmplPeriods() {
		return this.revenueEmplPeriods;
	}

	public void setRevenueEmplPeriods(Set<RevenueEmplPeriod> revenueEmplPeriods) {
		this.revenueEmplPeriods = revenueEmplPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<EmplDeptPeriod> getEmplDeptPeriods() {
		return this.emplDeptPeriods;
	}

	public void setEmplDeptPeriods(Set<EmplDeptPeriod> emplDeptPeriods) {
		this.emplDeptPeriods = emplDeptPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<EmployeeSalary> getEmployeeSalaries() {
		return this.employeeSalaries;
	}

	public void setEmployeeSalaries(Set<EmployeeSalary> employeeSalaries) {
		this.employeeSalaries = employeeSalaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<EmployeeSettings> getEmployeeSettingses() {
		return this.employeeSettingses;
	}

	public void setEmployeeSettingses(Set<EmployeeSettings> employeeSettingses) {
		this.employeeSettingses = employeeSettingses;
	}

}
