package com.consultancygrid.trz.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MatchcodeListId generated by hbm2java
 */
@Embeddable
public class MatchcodeListId implements java.io.Serializable {

	private String matchcode;
	private String firstName;
	private String lastName;

	public MatchcodeListId() {
	}

	public MatchcodeListId(String matchcode, String lastName) {
		this.matchcode = matchcode;
		this.lastName = lastName;
	}

	public MatchcodeListId(String matchcode, String firstName, String lastName) {
		this.matchcode = matchcode;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	@Column(name = "MATCHCODE", nullable = false, length = 40)
	public String getMatchcode() {
		return this.matchcode;
	}

	public void setMatchcode(String matchcode) {
		this.matchcode = matchcode;
	}

	@Column(name = "FIRST_NAME", length = 120)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 120)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatchcodeListId))
			return false;
		MatchcodeListId castOther = (MatchcodeListId) other;

		return ((this.getMatchcode() == castOther.getMatchcode()) || (this
				.getMatchcode() != null && castOther.getMatchcode() != null && this
				.getMatchcode().equals(castOther.getMatchcode())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this
						.getFirstName() != null
						&& castOther.getFirstName() != null && this
						.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this
						.getLastName() != null
						&& castOther.getLastName() != null && this
						.getLastName().equals(castOther.getLastName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMatchcode() == null ? 0 : this.getMatchcode().hashCode());
		result = 37 * result
				+ (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result
				+ (getLastName() == null ? 0 : this.getLastName().hashCode());
		return result;
	}

}
