package com.consultancygrid.trz.model;

// Generated Oct 20, 2014 12:53:50 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * Period generated by hbm2java
 */
@Entity
@Table(name = "PERIOD")
public class Period implements java.io.Serializable {

	private UUID id;
	private String code;
	private Date dateStart;
	private Date dateEnd;
	private BigDecimal revenue;
	private Set<EmployeeSettings> employeeSettingses = new HashSet<EmployeeSettings>(
			0);
	private Set<RevenueEmplPeriod> revenueEmplPeriods = new HashSet<RevenueEmplPeriod>(
			0);
	private Set<EmplDeptPeriod> emplDeptPeriods = new HashSet<EmplDeptPeriod>(0);
	private Set<EmployeeSalary> employeeSalaries = new HashSet<EmployeeSalary>(
			0);
	private Set<RevenueDeptPeriod> revenueDeptPeriods = new HashSet<RevenueDeptPeriod>(
			0);
	private Set<PeriodSetting> periodSettings = new HashSet<PeriodSetting>(0);

	public Period() {
	}

	public Period(UUID id, String code) {
		this.id = id;
		this.code = code;
	}

	public Period(UUID id, String code, Date dateStart, Date dateEnd,
			BigDecimal revenue, Set<EmployeeSettings> employeeSettingses,
			Set<RevenueEmplPeriod> revenueEmplPeriods,
			Set<EmplDeptPeriod> emplDeptPeriods,
			Set<EmployeeSalary> employeeSalaries,
			Set<RevenueDeptPeriod> revenueDeptPeriods,
			Set<PeriodSetting> periodSettings) {
		this.id = id;
		this.code = code;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.revenue = revenue;
		this.employeeSettingses = employeeSettingses;
		this.revenueEmplPeriods = revenueEmplPeriods;
		this.emplDeptPeriods = emplDeptPeriods;
		this.employeeSalaries = employeeSalaries;
		this.revenueDeptPeriods = revenueDeptPeriods;
		this.periodSettings = periodSettings;
	}

	@GenericGenerator(name = "period_trz_uuid_gen", strategy = "com.consultancygrid.trz.model.CustomUUIDGenerator")
	@Id
	@GeneratedValue(generator = "period_trz_uuid_gen")
	@Type(type = "com.consultancygrid.trz.model.UUIDType")
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "CODE", nullable = false, length = 28)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_START", length = 7)
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_END", length = 7)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	@Column(name = "REVENUE", precision = 22, scale = 0)
	public BigDecimal getRevenue() {
		return this.revenue;
	}

	public void setRevenue(BigDecimal revenue) {
		this.revenue = revenue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	public Set<EmployeeSettings> getEmployeeSettingses() {
		return this.employeeSettingses;
	}

	public void setEmployeeSettingses(Set<EmployeeSettings> employeeSettingses) {
		this.employeeSettingses = employeeSettingses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	public Set<RevenueEmplPeriod> getRevenueEmplPeriods() {
		return this.revenueEmplPeriods;
	}

	public void setRevenueEmplPeriods(Set<RevenueEmplPeriod> revenueEmplPeriods) {
		this.revenueEmplPeriods = revenueEmplPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	public Set<EmplDeptPeriod> getEmplDeptPeriods() {
		return this.emplDeptPeriods;
	}

	public void setEmplDeptPeriods(Set<EmplDeptPeriod> emplDeptPeriods) {
		this.emplDeptPeriods = emplDeptPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	public Set<EmployeeSalary> getEmployeeSalaries() {
		return this.employeeSalaries;
	}

	public void setEmployeeSalaries(Set<EmployeeSalary> employeeSalaries) {
		this.employeeSalaries = employeeSalaries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	public Set<RevenueDeptPeriod> getRevenueDeptPeriods() {
		return this.revenueDeptPeriods;
	}

	public void setRevenueDeptPeriods(Set<RevenueDeptPeriod> revenueDeptPeriods) {
		this.revenueDeptPeriods = revenueDeptPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "period")
	public Set<PeriodSetting> getPeriodSettings() {
		return this.periodSettings;
	}

	public void setPeriodSettings(Set<PeriodSetting> periodSettings) {
		this.periodSettings = periodSettings;
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		
		Period other = (Period) obj;
		if (other == null) {
			return false;
		}
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		return true;
	}

	
}
