package com.consultancygrid.trz.model;

// Generated Oct 20, 2014 12:53:50 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * RevenueEmplPeriod generated by hbm2java
 */
@Entity
@Table(name = "REVENUE_EMPL_PERIOD", uniqueConstraints = @UniqueConstraint(columnNames = {
		"FK_EMPLOYEE_ID", "FK_PERIOD_ID" }))
public class RevenueEmplPeriod implements java.io.Serializable {

	private UUID id;
	private Employee employee;
	private Period period;
	private BigDecimal revenue;

	public RevenueEmplPeriod() {
	}

	public RevenueEmplPeriod(UUID id, Employee employee, Period period) {
		this.id = id;
		this.employee = employee;
		this.period = period;
	}

	public RevenueEmplPeriod(UUID id, Employee employee, Period period,
			BigDecimal revenue) {
		this.id = id;
		this.employee = employee;
		this.period = period;
		this.revenue = revenue;
	}

	@GenericGenerator(name = "rep_trz_uuid_gen", strategy = "com.consultancygrid.trz.model.CustomUUIDGenerator")
	@Id
	@GeneratedValue(generator = "rep_trz_uuid_gen")
	@Type(type = "com.consultancygrid.trz.model.UUIDType")
	@Column(name = "ID", unique = true, nullable = false, length = 144)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_EMPLOYEE_ID", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_PERIOD_ID", nullable = false)
	public Period getPeriod() {
		return this.period;
	}

	public void setPeriod(Period period) {
		this.period = period;
	}

	@Column(name = "REVENUE", precision = 22, scale = 0)
	public BigDecimal getRevenue() {
		return this.revenue;
	}

	public void setRevenue(BigDecimal revenue) {
		this.revenue = revenue;
	}

}
