package com.consultancygrid.trz.model;

// Generated Feb 8, 2015 1:19:13 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * TargetPeriod generated by hbm2java
 */
@Entity
@Table(name = "TARGET_PERIOD", uniqueConstraints = @UniqueConstraint(columnNames = "CODE"))
public class TargetPeriod implements java.io.Serializable {

	private UUID id;
	private String code;
	private Date dateStart;
	private Date dateEnd;
	private BigDecimal periodLength;
	private Set<TargetEmplPeriod> targetEmplPeriods = new HashSet<TargetEmplPeriod>(
			0);
	private Set<TargetLevels> targetLevelses = new HashSet<TargetLevels>(0);

	public TargetPeriod() {
	}

	public TargetPeriod(UUID id, String code, Date dateStart, Date dateEnd,
			BigDecimal periodLength) {
		this.id = id;
		this.code = code;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.periodLength = periodLength;
	}

	public TargetPeriod(UUID id, String code, Date dateStart, Date dateEnd,
			BigDecimal periodLength, Set<TargetEmplPeriod> targetEmplPeriods,
			Set<TargetLevels> targetLevelses) {
		this.id = id;
		this.code = code;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.periodLength = periodLength;
		this.targetEmplPeriods = targetEmplPeriods;
		this.targetLevelses = targetLevelses;
	}

	
	@GenericGenerator(name = "trgPer_trz_uuid_gen", strategy = "com.consultancygrid.trz.model.CustomUUIDGenerator")
	@Id
	@GeneratedValue(generator = "trgPer_trz_uuid_gen")
	@Type(type = "com.consultancygrid.trz.model.UUIDType")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "CODE", unique = true, nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_START", nullable = false, length = 7)
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_END", nullable = false, length = 7)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	@Column(name = "PERIOD_LENGTH", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPeriodLength() {
		return this.periodLength;
	}

	public void setPeriodLength(BigDecimal periodLength) {
		this.periodLength = periodLength;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "targetPeriod")
	public Set<TargetEmplPeriod> getTargetEmplPeriods() {
		return this.targetEmplPeriods;
	}

	public void setTargetEmplPeriods(Set<TargetEmplPeriod> targetEmplPeriods) {
		this.targetEmplPeriods = targetEmplPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "targetPeriod")
	public Set<TargetLevels> getTargetLevelses() {
		return this.targetLevelses;
	}

	public void setTargetLevelses(Set<TargetLevels> targetLevelses) {
		this.targetLevelses = targetLevelses;
	}

}
