package com.consultancygrid.trz.model;

// Generated Feb 8, 2015 1:19:13 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

/**
 * TargetLevels generated by hbm2java
 */
@Entity
@Table(name = "TARGET_LEVELS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"FK_TARGET_PERIOD_ID", "TARGET_PERCENT" }))
public class TargetLevels implements java.io.Serializable {

	private UUID id;
	private TargetPeriod targetPeriod;
	private BigDecimal targetPercent;
	private BigDecimal targetBonus;

	public TargetLevels() {
	}

	public TargetLevels(UUID id, TargetPeriod targetPeriod,
			BigDecimal targetPercent, BigDecimal targetBonus) {
		this.id = id;
		this.targetPeriod = targetPeriod;
		this.targetPercent = targetPercent;
		this.targetBonus = targetBonus;
	}

	@GenericGenerator(name = "trgLvl_trz_uuid_gen", strategy = "com.consultancygrid.trz.model.CustomUUIDGenerator")
	@Id
	@GeneratedValue(generator = "trgLvl_trz_uuid_gen")
	@Type(type = "com.consultancygrid.trz.model.UUIDType")
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_TARGET_PERIOD_ID", nullable = false)
	public TargetPeriod getTargetPeriod() {
		return this.targetPeriod;
	}

	public void setTargetPeriod(TargetPeriod targetPeriod) {
		this.targetPeriod = targetPeriod;
	}

	@Column(name = "TARGET_PERCENT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTargetPercent() {
		return this.targetPercent;
	}

	public void setTargetPercent(BigDecimal targetPercent) {
		this.targetPercent = targetPercent;
	}

	@Column(name = "TARGET_BONUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTargetBonus() {
		return this.targetBonus;
	}

	public void setTargetBonus(BigDecimal targetBonus) {
		this.targetBonus = targetBonus;
	}

}
